repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [-d, "{extends: relaxed, rules: {line-length: disable}}"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        args: ["--ignore", "DL3008", "--ignore", "DL3007", "--ignore", "DL3041", "--ignore", "DL3013", "--ignore", "DL4006", "--ignore", "DL3059"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.0
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: commitizen-branch
        name: commitizen check branch
        entry: >-
          bash -c 'if [ -n "$PRE_COMMIT_FROM_REF" ]; then .venv/bin/cz check --rev-range "$PRE_COMMIT_FROM_REF..$PRE_COMMIT_TO_REF"; else echo "Skipping branch check: no revision range provided."; fi'
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: mypy
        name: mypy
        entry: make typecheck
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
      - id: lint-check
        name: lint check
        entry: make check-lint
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
