repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: make typecheck
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
      - id: lint-check
        name: lint check
        entry: make check-lint
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]