"""add_codec_and_tracks

Revision ID: 0b15dec92438
Revises: ce128c6d8aec
Create Date: 2026-05-28 12:43:26.587053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b15dec92438"
down_revision: Union[str, Sequence[str], None] = "ce128c6d8aec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("video_codec", sa.String(), nullable=True))
    op.add_column("episodes", sa.Column("resolution", sa.String(), nullable=True))
    op.add_column("episodes", sa.Column("audio_tracks", sa.String(), nullable=True))
    op.add_column("episodes", sa.Column("subtitle_tracks", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("video_codec", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("resolution", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("audio_tracks", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("subtitle_tracks", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "subtitle_tracks")
    op.drop_column("movies", "audio_tracks")
    op.drop_column("movies", "resolution")
    op.drop_column("movies", "video_codec")
    op.drop_column("episodes", "subtitle_tracks")
    op.drop_column("episodes", "audio_tracks")
    op.drop_column("episodes", "resolution")
    op.drop_column("episodes", "video_codec")
    # ### end Alembic commands ###
