"""add_movies_table

Revision ID: 1d504caf3889
Revises: e5421f98bc12
Create Date: 2026-05-13 13:52:55.303235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d504caf3889"
down_revision: Union[str, Sequence[str], None] = "e5421f98bc12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("library_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("jellyfin_id", sa.String(), nullable=True),
        sa.Column("tmdb_identifier", sa.String(), nullable=True),
        sa.Column("poster_path", sa.String(), nullable=True),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("tmdb_name", sa.String(), nullable=True),
        sa.Column("locked_metadata", sa.Boolean(), nullable=True),
        sa.Column("date_added", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("rating", sa.String(), nullable=True),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("watched", sa.Boolean(), nullable=True),
        sa.Column("last_played_position", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_name", "name", name="uq_movies_library_name_name"),
        sa.UniqueConstraint("path"),
    )
    op.create_index("idx_movies_jellyfin_id", "movies", ["jellyfin_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_movies_jellyfin_id", table_name="movies")
    op.drop_table("movies")
    # ### end Alembic commands ###
