"""add_mapping_indexes

Revision ID: 36e082ff742e
Revises: 2e8292adc104
Create Date: 2026-06-15 13:31:02.587387

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "36e082ff742e"
down_revision: Union[str, Sequence[str], None] = "2e8292adc104"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_metadata_file_mappings_episode",
        "metadata_file_mappings",
        ["episode_id", "media_file_id"],
        unique=False,
    )
    op.create_index(
        "idx_metadata_file_mappings_movie",
        "metadata_file_mappings",
        ["movie_id", "media_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_metadata_file_mappings_movie", table_name="metadata_file_mappings"
    )
    op.drop_index(
        "idx_metadata_file_mappings_episode", table_name="metadata_file_mappings"
    )
    # ### end Alembic commands ###
