"""add_smart_row_cache_table

Revision ID: 5a4f124e8aed
Revises: 0def24d4a3b4
Create Date: 2026-06-29 14:09:43.004406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a4f124e8aed"
down_revision: Union[str, Sequence[str], None] = "0def24d4a3b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smart_row_cache",
        sa.Column("id", sa.LargeBinary(), nullable=False),
        sa.Column("config_hash", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("series_id", sa.LargeBinary(), nullable=True),
        sa.Column("movie_id", sa.LargeBinary(), nullable=True),
        sa.Column("season_name", sa.String(), nullable=True),
        sa.Column("date_added", sa.Integer(), nullable=False),
        sa.Column("air_date", sa.String(), nullable=True),
        sa.Column("watched_count", sa.Integer(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("last_played_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_smart_row_cache_config",
        "smart_row_cache",
        ["config_hash", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_row_cache_config_hash"),
        "smart_row_cache",
        ["config_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_row_cache_movie_id"),
        "smart_row_cache",
        ["movie_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_row_cache_series_id"),
        "smart_row_cache",
        ["series_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_smart_row_cache_series_id"), table_name="smart_row_cache")
    op.drop_index(op.f("ix_smart_row_cache_movie_id"), table_name="smart_row_cache")
    op.drop_index(op.f("ix_smart_row_cache_config_hash"), table_name="smart_row_cache")
    op.drop_index("idx_smart_row_cache_config", table_name="smart_row_cache")
    op.drop_table("smart_row_cache")
    # ### end Alembic commands ###
