"""add runtime column to media_files

Revision ID: 701d935de074
Revises: 49d186288d29
Create Date: 2026-06-11 16:30:07.920151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "701d935de074"
down_revision: Union[str, Sequence[str], None] = "49d186288d29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_files", sa.Column("runtime", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_files", "runtime")
    # ### end Alembic commands ###
