"""add_air_date_columns

Revision ID: 8dbcde9fc7de
Revises: cd94beb4248b
Create Date: 2026-05-12 11:11:18.236704

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8dbcde9fc7de"
down_revision: str | Sequence[str] | None = "cd94beb4248b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("air_date", sa.String(), nullable=True))
    op.add_column("series", sa.Column("first_air_date", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("series", "first_air_date")
    op.drop_column("episodes", "air_date")
    # ### end Alembic commands ###
