"""add_tmdb_episode_group_id

Revision ID: 90c0fcb92ee7
Revises: 0b15dec92438
Create Date: 2026-06-03 12:25:40.787417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90c0fcb92ee7"
down_revision: Union[str, Sequence[str], None] = "0b15dec92438"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "series", sa.Column("tmdb_episode_group_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("series", "tmdb_episode_group_id")
    # ### end Alembic commands ###
