"""add_cast_crew_image_tables

Revision ID: b7c8d9e0f1a2
Revises: 5a4f124e8aed
Create Date: 2026-07-01 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7c8d9e0f1a2"
down_revision: Union[str, Sequence[str], None] = "5a4f124e8aed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create people table
    op.create_table(
        "people",
        sa.Column("id", sa.LargeBinary(), nullable=False),
        sa.Column("tmdb_identifier", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("profile_path", sa.String(length=512), nullable=True),
        sa.Column("biography", sa.String(), nullable=True),
        sa.Column("birth_date", sa.String(length=10), nullable=True),
        sa.Column("death_date", sa.String(length=10), nullable=True),
        sa.Column("place_of_birth", sa.String(length=255), nullable=True),
        sa.Column("also_known_as", sa.String(), nullable=True),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_identifier"),
    )
    op.create_index(
        op.f("ix_people_tmdb_identifier"),
        "people",
        ["tmdb_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_people_name"),
        "people",
        ["name"],
        unique=False,
    )

    # 2. Create media_cast table
    op.create_table(
        "media_cast",
        sa.Column("id", sa.LargeBinary(), nullable=False),
        sa.Column("person_id", sa.LargeBinary(), nullable=False),
        sa.Column("series_id", sa.LargeBinary(), nullable=True),
        sa.Column("season_id", sa.LargeBinary(), nullable=True),
        sa.Column("episode_id", sa.LargeBinary(), nullable=True),
        sa.Column("movie_id", sa.LargeBinary(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("character", sa.String(length=255), nullable=True),
        sa.Column("job", sa.String(length=255), nullable=True),
        sa.Column("department", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("tmdb_credit_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "person_id",
            "series_id",
            "role",
            "tmdb_credit_id",
            name="uq_media_cast_person_series",
        ),
        sa.UniqueConstraint(
            "person_id",
            "movie_id",
            "role",
            "tmdb_credit_id",
            name="uq_media_cast_person_movie",
        ),
    )
    op.create_index(
        op.f("ix_media_cast_person_id"),
        "media_cast",
        ["person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_cast_series_id"),
        "media_cast",
        ["series_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_cast_season_id"),
        "media_cast",
        ["season_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_cast_episode_id"),
        "media_cast",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_cast_movie_id"),
        "media_cast",
        ["movie_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_cast_role"),
        "media_cast",
        ["role"],
        unique=False,
    )

    # 3. Create media_images table
    op.create_table(
        "media_images",
        sa.Column("id", sa.LargeBinary(), nullable=False),
        sa.Column("series_id", sa.LargeBinary(), nullable=True),
        sa.Column("movie_id", sa.LargeBinary(), nullable=True),
        sa.Column("image_type", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("remote_url", sa.String(length=512), nullable=True),
        sa.Column("local_path", sa.String(length=512), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_images_series_id"),
        "media_images",
        ["series_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_images_movie_id"),
        "media_images",
        ["movie_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_images_image_type"),
        "media_images",
        ["image_type"],
        unique=False,
    )

    # 4. Add rating and genre columns to series table
    op.add_column(
        "series",
        sa.Column("rating", sa.String(), nullable=True),
    )
    op.add_column(
        "series",
        sa.Column("genre", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("series", "genre")
    op.drop_column("series", "rating")

    op.drop_index(op.f("ix_media_images_image_type"), table_name="media_images")
    op.drop_index(op.f("ix_media_images_movie_id"), table_name="media_images")
    op.drop_index(op.f("ix_media_images_series_id"), table_name="media_images")
    op.drop_table("media_images")

    op.drop_index(op.f("ix_media_cast_role"), table_name="media_cast")
    op.drop_index(op.f("ix_media_cast_movie_id"), table_name="media_cast")
    op.drop_index(op.f("ix_media_cast_episode_id"), table_name="media_cast")
    op.drop_index(op.f("ix_media_cast_season_id"), table_name="media_cast")
    op.drop_index(op.f("ix_media_cast_series_id"), table_name="media_cast")
    op.drop_index(op.f("ix_media_cast_person_id"), table_name="media_cast")
    op.drop_table("media_cast")

    op.drop_index(op.f("ix_people_name"), table_name="people")
    op.drop_index(op.f("ix_people_tmdb_identifier"), table_name="people")
    op.drop_table("people")
    # ### end Alembic commands ###
