"""add_readability_columns

Revision ID: bbd1b7ccd143
Revises: b7c8d9e0f1a2
Create Date: 2026-07-07 09:55:34.299179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbd1b7ccd143"
down_revision: Union[str, Sequence[str], None] = "b7c8d9e0f1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("series_name", sa.String(), nullable=True))
    op.add_column("episodes", sa.Column("season_name", sa.String(), nullable=True))
    op.add_column("seasons", sa.Column("series_name", sa.String(), nullable=True))

    op.add_column(
        "playback_states", sa.Column("series_name", sa.String(), nullable=True)
    )
    op.add_column(
        "playback_states", sa.Column("season_name", sa.String(), nullable=True)
    )
    op.add_column(
        "playback_states", sa.Column("episode_name", sa.String(), nullable=True)
    )
    op.add_column(
        "playback_states", sa.Column("movie_name", sa.String(), nullable=True)
    )

    op.add_column(
        "metadata_file_mappings", sa.Column("file_path", sa.String(), nullable=True)
    )
    op.add_column(
        "metadata_file_mappings", sa.Column("series_name", sa.String(), nullable=True)
    )
    op.add_column(
        "metadata_file_mappings", sa.Column("season_name", sa.String(), nullable=True)
    )
    op.add_column(
        "metadata_file_mappings", sa.Column("episode_name", sa.String(), nullable=True)
    )
    op.add_column(
        "metadata_file_mappings", sa.Column("movie_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###

    # Populate existing rows
    op.execute(
        """
        UPDATE seasons
        SET series_name = (SELECT name FROM series WHERE id = seasons.series_id)
        WHERE series_name IS NULL;
        """
    )
    op.execute(
        """
        UPDATE episodes
        SET season_name = (SELECT name FROM seasons WHERE id = episodes.season_id),
            series_name = (SELECT series_name FROM seasons WHERE id = episodes.season_id)
        WHERE season_name IS NULL OR series_name IS NULL;
        """
    )
    op.execute(
        """
        UPDATE playback_states
        SET episode_name = (SELECT name FROM episodes WHERE id = playback_states.episode_id),
            season_name = (SELECT season_name FROM episodes WHERE id = playback_states.episode_id),
            series_name = (SELECT series_name FROM episodes WHERE id = playback_states.episode_id),
            movie_name = (SELECT name FROM movies WHERE id = playback_states.movie_id)
        WHERE episode_name IS NULL OR movie_name IS NULL;
        """
    )
    op.execute(
        """
        UPDATE metadata_file_mappings
        SET file_path = (SELECT path FROM media_files WHERE id = metadata_file_mappings.media_file_id),
            episode_name = (SELECT name FROM episodes WHERE id = metadata_file_mappings.episode_id),
            season_name = (SELECT season_name FROM episodes WHERE id = metadata_file_mappings.episode_id),
            series_name = (SELECT series_name FROM episodes WHERE id = metadata_file_mappings.episode_id),
            movie_name = (SELECT name FROM movies WHERE id = metadata_file_mappings.movie_id)
        WHERE file_path IS NULL;
        """
    )

    # Database-level triggers to keep names updated and prevent data drift
    op.execute(
        """
        CREATE TRIGGER update_series_name_in_seasons
        AFTER UPDATE OF name ON series
        BEGIN
            UPDATE seasons
            SET series_name = NEW.name
            WHERE series_id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_series_name_in_episodes
        AFTER UPDATE OF name ON series
        BEGIN
            UPDATE episodes
            SET series_name = NEW.name
            WHERE season_id IN (SELECT id FROM seasons WHERE series_id = NEW.id);
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_series_name_in_playback_states
        AFTER UPDATE OF name ON series
        BEGIN
            UPDATE playback_states
            SET series_name = NEW.name
            WHERE episode_id IN (SELECT id FROM episodes WHERE season_id IN (SELECT id FROM seasons WHERE series_id = NEW.id));
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_series_name_in_file_mappings
        AFTER UPDATE OF name ON series
        BEGIN
            UPDATE metadata_file_mappings
            SET series_name = NEW.name
            WHERE episode_id IN (SELECT id FROM episodes WHERE season_id IN (SELECT id FROM seasons WHERE series_id = NEW.id));
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER update_season_name_in_episodes
        AFTER UPDATE OF name ON seasons
        BEGIN
            UPDATE episodes
            SET season_name = NEW.name
            WHERE season_id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_season_name_in_playback_states
        AFTER UPDATE OF name ON seasons
        BEGIN
            UPDATE playback_states
            SET season_name = NEW.name
            WHERE episode_id IN (SELECT id FROM episodes WHERE season_id = NEW.id);
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_season_name_in_file_mappings
        AFTER UPDATE OF name ON seasons
        BEGIN
            UPDATE metadata_file_mappings
            SET season_name = NEW.name
            WHERE episode_id IN (SELECT id FROM episodes WHERE season_id = NEW.id);
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER update_episode_fields_in_playback_states
        AFTER UPDATE OF name, season_name, series_name ON episodes
        BEGIN
            UPDATE playback_states
            SET episode_name = NEW.name,
                season_name = NEW.season_name,
                series_name = NEW.series_name
            WHERE episode_id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_episode_fields_in_file_mappings
        AFTER UPDATE OF name, season_name, series_name ON episodes
        BEGIN
            UPDATE metadata_file_mappings
            SET episode_name = NEW.name,
                season_name = NEW.season_name,
                series_name = NEW.series_name
            WHERE episode_id = NEW.id;
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER update_movie_fields_in_playback_states
        AFTER UPDATE OF name ON movies
        BEGIN
            UPDATE playback_states
            SET movie_name = NEW.name
            WHERE movie_id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_movie_fields_in_file_mappings
        AFTER UPDATE OF name ON movies
        BEGIN
            UPDATE metadata_file_mappings
            SET movie_name = NEW.name
            WHERE movie_id = NEW.id;
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER update_media_file_path_in_file_mappings
        AFTER UPDATE OF path ON media_files
        BEGIN
            UPDATE metadata_file_mappings
            SET file_path = NEW.path
            WHERE media_file_id = NEW.id;
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER insert_season_series_name
        AFTER INSERT ON seasons
        BEGIN
            UPDATE seasons
            SET series_name = (SELECT name FROM series WHERE id = NEW.series_id)
            WHERE id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_season_series_name
        AFTER UPDATE OF series_id ON seasons
        BEGIN
            UPDATE seasons
            SET series_name = (SELECT name FROM series WHERE id = NEW.series_id)
            WHERE id = NEW.id;
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER insert_episode_season_and_series_name
        AFTER INSERT ON episodes
        BEGIN
            UPDATE episodes
            SET season_name = (SELECT name FROM seasons WHERE id = NEW.season_id),
                series_name = (SELECT series_name FROM seasons WHERE id = NEW.season_id)
            WHERE id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_episode_season_and_series_name
        AFTER UPDATE OF season_id ON episodes
        BEGIN
            UPDATE episodes
            SET season_name = (SELECT name FROM seasons WHERE id = NEW.season_id),
                series_name = (SELECT series_name FROM seasons WHERE id = NEW.season_id)
            WHERE id = NEW.id;
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER insert_playback_state_names
        AFTER INSERT ON playback_states
        BEGIN
            UPDATE playback_states
            SET episode_name = (SELECT name FROM episodes WHERE id = NEW.episode_id),
                season_name = (SELECT season_name FROM episodes WHERE id = NEW.episode_id),
                series_name = (SELECT series_name FROM episodes WHERE id = NEW.episode_id),
                movie_name = (SELECT name FROM movies WHERE id = NEW.movie_id)
            WHERE id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_playback_state_names
        AFTER UPDATE OF episode_id, movie_id ON playback_states
        BEGIN
            UPDATE playback_states
            SET episode_name = (SELECT name FROM episodes WHERE id = NEW.episode_id),
                season_name = (SELECT season_name FROM episodes WHERE id = NEW.episode_id),
                series_name = (SELECT series_name FROM episodes WHERE id = NEW.episode_id),
                movie_name = (SELECT name FROM movies WHERE id = NEW.movie_id)
            WHERE id = NEW.id;
        END;
        """
    )

    op.execute(
        """
        CREATE TRIGGER insert_file_mapping_names
        AFTER INSERT ON metadata_file_mappings
        BEGIN
            UPDATE metadata_file_mappings
            SET file_path = (SELECT path FROM media_files WHERE id = NEW.media_file_id),
                episode_name = (SELECT name FROM episodes WHERE id = NEW.episode_id),
                season_name = (SELECT season_name FROM episodes WHERE id = NEW.episode_id),
                series_name = (SELECT series_name FROM episodes WHERE id = NEW.episode_id),
                movie_name = (SELECT name FROM movies WHERE id = NEW.movie_id)
            WHERE id = NEW.id;
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_file_mapping_names
        AFTER UPDATE OF media_file_id, episode_id, movie_id ON metadata_file_mappings
        BEGIN
            UPDATE metadata_file_mappings
            SET file_path = (SELECT path FROM media_files WHERE id = NEW.media_file_id),
                episode_name = (SELECT name FROM episodes WHERE id = NEW.episode_id),
                season_name = (SELECT season_name FROM episodes WHERE id = NEW.episode_id),
                series_name = (SELECT series_name FROM episodes WHERE id = NEW.episode_id),
                movie_name = (SELECT name FROM movies WHERE id = NEW.movie_id)
            WHERE id = NEW.id;
        END;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_file_mapping_names;")
    op.execute("DROP TRIGGER IF EXISTS insert_file_mapping_names;")
    op.execute("DROP TRIGGER IF EXISTS update_playback_state_names;")
    op.execute("DROP TRIGGER IF EXISTS insert_playback_state_names;")
    op.execute("DROP TRIGGER IF EXISTS update_episode_season_and_series_name;")
    op.execute("DROP TRIGGER IF EXISTS insert_episode_season_and_series_name;")
    op.execute("DROP TRIGGER IF EXISTS update_season_series_name;")
    op.execute("DROP TRIGGER IF EXISTS insert_season_series_name;")
    op.execute("DROP TRIGGER IF EXISTS update_media_file_path_in_file_mappings;")
    op.execute("DROP TRIGGER IF EXISTS update_movie_fields_in_file_mappings;")
    op.execute("DROP TRIGGER IF EXISTS update_movie_fields_in_playback_states;")
    op.execute("DROP TRIGGER IF EXISTS update_episode_fields_in_file_mappings;")
    op.execute("DROP TRIGGER IF EXISTS update_episode_fields_in_playback_states;")
    op.execute("DROP TRIGGER IF EXISTS update_season_name_in_file_mappings;")
    op.execute("DROP TRIGGER IF EXISTS update_season_name_in_playback_states;")
    op.execute("DROP TRIGGER IF EXISTS update_season_name_in_episodes;")
    op.execute("DROP TRIGGER IF EXISTS update_series_name_in_file_mappings;")
    op.execute("DROP TRIGGER IF EXISTS update_series_name_in_playback_states;")
    op.execute("DROP TRIGGER IF EXISTS update_series_name_in_episodes;")
    op.execute("DROP TRIGGER IF EXISTS update_series_name_in_seasons;")

    op.drop_column("metadata_file_mappings", "movie_name")
    op.drop_column("metadata_file_mappings", "episode_name")
    op.drop_column("metadata_file_mappings", "season_name")
    op.drop_column("metadata_file_mappings", "series_name")
    op.drop_column("metadata_file_mappings", "file_path")

    op.drop_column("playback_states", "movie_name")
    op.drop_column("playback_states", "episode_name")
    op.drop_column("playback_states", "season_name")
    op.drop_column("playback_states", "series_name")

    op.drop_column("seasons", "series_name")
    op.drop_column("episodes", "season_name")
    op.drop_column("episodes", "series_name")
    # ### end Alembic commands ###
