"""Initial revision

Revision ID: cd94beb4248b
Revises:
Create Date: 2026-05-08 15:53:18.551177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd94beb4248b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("library_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("jellyfin_id", sa.String(), nullable=True),
        sa.Column("tmdb_identifier", sa.String(), nullable=True),
        sa.Column("poster_path", sa.String(), nullable=True),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("tmdb_name", sa.String(), nullable=True),
        sa.Column("locked_metadata", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_name", "name", name="uq_series_library_name_name"),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("jellyfin_id", sa.String(), nullable=True),
        sa.Column("poster_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "name", name="uq_seasons_series_id_name"),
    )
    op.create_index("idx_seasons_series_id", "seasons", ["series_id"], unique=False)
    op.create_table(
        "episodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("jellyfin_id", sa.String(), nullable=True),
        sa.Column("tmdb_episode_identifier", sa.String(), nullable=True),
        sa.Column("tmdb_name", sa.String(), nullable=True),
        sa.Column("tmdb_number", sa.Integer(), nullable=True),
        sa.Column("watched", sa.Boolean(), nullable=True),
        sa.Column("date_added", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
        sa.UniqueConstraint("season_id", "name", name="uq_episodes_season_id_name"),
    )
    op.create_index(
        "idx_episodes_jellyfin_id", "episodes", ["jellyfin_id"], unique=False
    )
    op.create_index("idx_episodes_season_id", "episodes", ["season_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_episodes_season_id", table_name="episodes")
    op.drop_index("idx_episodes_jellyfin_id", table_name="episodes")
    op.drop_table("episodes")
    op.drop_index("idx_seasons_series_id", table_name="seasons")
    op.drop_table("seasons")
    op.drop_table("series")
    # ### end Alembic commands ###
