"""add_episodes_runtime

Revision ID: fa4ad8226f3a
Revises: 1d504caf3889
Create Date: 2026-05-13 22:56:08.612923

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fa4ad8226f3a"
down_revision: str | Sequence[str] | None = "1d504caf3889"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("runtime", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("episodes", "runtime")
    # ### end Alembic commands ###
