"""add_episodes_runtime

Revision ID: fa4ad8226f3a
Revises: 1d504caf3889
Create Date: 2026-05-13 22:56:08.612923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa4ad8226f3a"
down_revision: Union[str, Sequence[str], None] = "1d504caf3889"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("runtime", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("episodes", "runtime")
    # ### end Alembic commands ###
