ARG TEST_OS_VERSION=latest
FROM fedora:${TEST_OS_VERSION}
# Install bootstrapping and system dependencies
RUN dnf update -y && dnf install -y \
    git \
    make \
    tar \
    xz \
    findutils \
    shadow-utils \
    binutils \
    curl \
    vlc \
    /usr/bin/ffmpeg \
    /usr/bin/ffprobe \
    mesa-libGL-devel \
    mesa-libEGL-devel \
    libxkbcommon-x11 \
    xcb-util-wm \
    xcb-util-image \
    xcb-util-keysyms \
    xcb-util-renderutil \
    && dnf clean all

# Install uv for Python environment management
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

# Install the required Python version via uv
RUN uv python install

# Copy the codebase and pre-sync Python dependencies
WORKDIR /app
COPY . /app
RUN uv sync

# Build the executable
RUN uv run pyinstaller --noconfirm lan-streamer.spec
