name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint & Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for commit message checking

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Run lint
        run: make check-lint

      - name: Run typecheck
        run: make typecheck

      - name: Run all other linters (pre-commit)
        run: uv run pre-commit run --all-files --show-diff-on-failure

      - name: Verify commit messages (Push)
        if: github.event_name == 'push' && github.ref_name != 'main'
        run: |
          git fetch origin main --deepen=100
          uv run cz check --rev-range origin/main..HEAD

      - name: Verify commit messages (PR)
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }}
          uv run cz check --rev-range origin/${{ github.base_ref }}..HEAD
