name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ubuntu:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests with coverage check
        run: TEST_OS=ubuntu make test

      - name: Validate executable runs
        run: TEST_OS=ubuntu make validate-executable


  test-fedora:
    name: Test (Fedora)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: TEST_OS=fedora make test

      - name: Validate executable runs
        run: TEST_OS=fedora make validate-executable
